server:
  port: 8081

eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
  client:
    service-url:
      default-zone: http://${eureka.instance.hostname}:8761/eureka/
    register-with-eureka: true